# Generated by Django 3.1 on 2020-08-27 02:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200826_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
        migrations.AddField(
            model_name='category',
            name='color_text',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
